swagger: '2.0'
info:
  title: User Sign up APIs
  version: '0.1'
basePath: /v1
paths:
  /signup:
    post:
      summary: Sign up Api takes params and register user
      operationId: createUser
      consumes:
        - application/json
      parameters:
        - in: body
          description: user detail param here
          name: user
          required: true
          schema:
            $ref: '#/definitions/user-signup'
      responses:
        '200':
          description: 'Success'
          schema:
            $ref: '#/definitions/signup-success'
        '400':
          $ref: '#/responses/invalid-request'
      tags:
        - signup
  /current-time:
    get:
      summary: Sign up Api takes params and register user
      operationId: getCurrentTime
      parameters:
        - $ref: '#/parameters/name'
      responses:
        '200':
          description: 'Success'
          schema:
            $ref: '#/definitions/currenttime-success'
        '400':
          $ref: '#/responses/invalid-request'
      tags:
        - currenttime

definitions:
  user-signup:
    type: object
    title: user-signup
    description: properties to create a user
    required:
      - name
      - age
    properties:
      name:
        type: string
      age:
        type: number
  signup-success:
    type: object
    title: Signup success
    description: Signup success response object
    properties:
      name:
        type: string
  currenttime-success:
    type: object
    title: Current Time Success
    description: Time success response object
    properties:
      time:
        type: string
  error-response:
    type: object
    title: Error Response
    description: Standard error format
    properties:
      Code:
        type: string
      Message:
        type: string

responses:
  unauthorized:
    description: Unauthorized
    schema:
      $ref: '#/definitions/error-response'
  invalid-request:
    description: Invalid request
    schema:
      $ref: '#/definitions/error-response'
  forbidden:
    description: Insufficient privilege to execute action.
    schema:
      $ref: '#/definitions/error-response'
  not-found:
    description: Not found.
    schema:
      $ref: '#/definitions/error-response'
  conflict:
    description: Duplicate resource
    schema:
      $ref: '#/definitions/error-response'

parameters:
  name:
    name: name
    in: query
    type: string
    default: 'name'
  orderBy:
    name: orderBy
    in: query
    type: string
    default: 'createddate'
    pattern: '^[A-Za-z0-9_]+$'